name = "ben-ecosystem-ia"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
name = "ben-ecosystem-ia"

[[env.production.routes]]
pattern = "ecosystem.mauromoncao.adv.br/*"
zone_name = "mauromoncao.adv.br"
