import { Agent } from '../types'

// ─── Credenciais permitidas ──────────────────────────────────────────────────
export const ALLOWED_USERS = [
  { email: 'admin@mauromoncao.adv.br',             senha: process.env.EXPO_PUBLIC_AUTH_SENHA_1 || 'ben2026',  nome: 'Dr. Mauro Monção',      source: 'ecosystem' },
  { email: 'mauromoncaoestudos@gmail.com',          senha: process.env.EXPO_PUBLIC_AUTH_SENHA_2 || 'ben2026',  nome: 'Mauro Monção (Admin)',   source: 'gmail' },
  { email: 'mauromoncaoadv.escritorio@gmail.com',   senha: process.env.EXPO_PUBLIC_AUTH_SENHA_3 || 'ben2026',  nome: 'Escritório Admin',       source: 'escritorio' },
  { email: 'assistente@mauromoncao.adv.br',         senha: process.env.EXPO_PUBLIC_AUTH_SENHA_4 || 'assist2026', nome: 'Assistente Jurídico',  source: 'assistente' },
]

// ─── Emails de administrador ─────────────────────────────────────────────────
export const ADMIN_EMAILS = ['mauromoncaoestudos@gmail.com', 'mauromoncaoadv.escritorio@gmail.com']

// ─── Agentes restritos (apenas Admin) ────────────────────────────────────────
export const RESTRICTED_AGENTS = ['ben-perito-forense-profundo', 'ben-engenheiro-prompt']

// ─── URL base da API ─────────────────────────────────────────────────────────
export const API_BASE_URL = process.env.EXPO_PUBLIC_API_BASE_URL || 'https://ecosystem.mauromoncao.adv.br'

// ─── Todos os agentes do BEN Ecosystem ────────────────────────────────────────
export const ECOSYSTEM_AGENTS: Agent[] = [
  { id: 'ben-conteudista',            name: 'BEN Conteudista Jurídico',       emoji: '✍️',  description: 'Artigos jurídicos, posts e conteúdo institucional OAB-compliant.',    model: 'GPT-4o',             modelBadge: 'gpt',     category: 'marketing',  project: 'growth', color: '#7c3aed', active: true },
  { id: 'ben-estrategista-campanhas', name: 'BEN Estrategista Campanhas',     emoji: '📊', description: 'Análise de performance Meta Ads e Google Ads. ROI e KPIs.',           model: 'GPT-4o',             modelBadge: 'gpt',     category: 'marketing',  project: 'growth', color: '#059669', active: true },
  { id: 'ben-analista-relatorios',    name: 'BEN Analista de Relatórios',     emoji: '📈', description: 'Relatório semanal com insights de performance e métricas.',           model: 'Claude Haiku 4.5',   modelBadge: 'claude',  category: 'marketing',  project: 'growth', color: '#d97706', active: true },
  { id: 'ben-analista-monitoramento', name: 'BEN Analista Monitoramento',     emoji: '🔍', description: 'Monitoramento de saúde do sistema e alertas críticos.',               model: 'GPT-4o Mini',        modelBadge: 'gpt',     category: 'sistema',    project: 'growth', color: '#dc2626', active: true },
  { id: 'ben-estrategista-marketing', name: 'BEN Estrategista Marketing',     emoji: '📣', description: 'Redes sociais, Instagram, Reels e conteúdo OAB-compliant.',           model: 'GPT-4o',             modelBadge: 'gpt',     category: 'marketing',  project: 'growth', color: '#0369a1', active: true },
  { id: 'ben-diretor-criativo',       name: 'BEN Diretor Criativo',           emoji: '🎨', description: 'Identidade visual, branding jurídico e direção criativa.',            model: 'GPT-4o',             modelBadge: 'gpt',     category: 'marketing',  project: 'growth', color: '#7c3aed', active: true },
  { id: 'ben-revisor-juridico',       name: 'BEN Revisor Jurídico',           emoji: '📝', description: 'Revisão técnica e linguística de peças jurídicas.',                   model: 'Claude Haiku 4.5',   modelBadge: 'claude',  category: 'juridico',   project: 'growth', color: '#374151', active: true },
  { id: 'ben-peticionista',           name: 'BEN Peticionista',               emoji: '⚖️', description: 'Petições iniciais, recursos e peças de urgência do Growth.',          model: 'Claude Haiku 4.5',   modelBadge: 'claude',  category: 'juridico',   project: 'growth', color: '#1d4ed8', active: true },
  { id: 'ben-super-agente-juridico',      name: 'AGENTE OPERACIONAL MAXIMUS ⭐',  emoji: '🌟', description: 'Análise jurídica de máxima profundidade — última instância, análise final e vinculante.',         model: 'Claude Opus 4.6',    modelBadge: 'opus',    category: 'juridico',   project: 'juris',  color: '#92400e', active: true },
  { id: 'ben-agente-operacional-premium', name: 'AGENTE OPERACIONAL PREMIUM 🔷',  emoji: '💎', description: 'Análise jurídica moderada a profunda. Thinking adaptativo automático. Sinaliza casos para o Maximus.', model: 'Claude Sonnet 4.6',  modelBadge: 'sonnet',  category: 'juridico',   project: 'juris',  color: '#1d4ed8', active: true },
  { id: 'ben-peticionista-juridico',  name: 'BEN Peticionista Jurídico',      emoji: '⚖️', description: 'Peças processuais conforme o caso concreto e jurisprudência.',        model: 'Claude Haiku 4.5',   modelBadge: 'claude',  category: 'juridico',   project: 'juris',  color: '#1d4ed8', active: true },
  { id: 'ben-contratualista',         name: 'BEN Contratualista',             emoji: '📋', description: 'Contratos empresariais, NDAs, societários e documentos negociais.',   model: 'Claude Haiku 4.5',   modelBadge: 'claude',  category: 'juridico',   project: 'juris',  color: '#7c3aed', active: true },
  { id: 'ben-mandatario-juridico',    name: 'BEN Mandatário Jurídico',        emoji: '📜', description: 'Procurações Ad Judicia, gerais, especiais e substabelecimentos.',     model: 'Claude Haiku 4.5',   modelBadge: 'claude',  category: 'juridico',   project: 'juris',  color: '#059669', active: true },
  { id: 'ben-analista-processual',    name: 'BEN Analista Processual',        emoji: '🔬', description: 'Análise estratégica de processos com avaliação de risco.',            model: 'GPT-4o',             modelBadge: 'gpt',     category: 'juridico',   project: 'juris',  color: '#dc2626', active: true },
  { id: 'ben-auditor-processual',     name: 'BEN Auditor Processual',         emoji: '🔏', description: 'Auditoria de prazos críticos, conformidade OAB e gestão de risco.',  model: 'Claude Haiku 4.5',   modelBadge: 'claude',  category: 'juridico',   project: 'juris',  color: '#0f766e', active: true },
  { id: 'ben-gestor-juridico',        name: 'BEN Gestor Jurídico',            emoji: '🏢', description: 'Gestão de escritório, produtividade jurídica e governança.',          model: 'GPT-4o',             modelBadge: 'gpt',     category: 'juridico',   project: 'juris',  color: '#374151', active: true },
  { id: 'ben-tributarista',           name: 'BEN Tributarista',               emoji: '💰', description: 'Direito tributário, planejamento fiscal e teses avançadas.',          model: 'Claude Haiku 4.5',   modelBadge: 'claude',  category: 'juridico',   project: 'juris',  color: '#d97706', active: true },
  { id: 'ben-trabalhista',            name: 'BEN Trabalhista',                emoji: '👷', description: 'Direito do trabalho, TST, reclamações e acordos trabalhistas.',       model: 'GPT-4o',             modelBadge: 'gpt',     category: 'juridico',   project: 'juris',  color: '#0369a1', active: true },
  { id: 'ben-previdenciarista',       name: 'BEN Previdenciarista',           emoji: '🏛️', description: 'Benefícios INSS, aposentadorias e revisões previdenciárias.',         model: 'Claude Haiku 4.5',   modelBadge: 'claude',  category: 'juridico',   project: 'juris',  color: '#7c3aed', active: true },
  { id: 'ben-pesquisador-juridico',   name: 'BEN Pesquisador Jurídico',       emoji: '🔎', description: 'Pesquisa em tempo real: STF, STJ, TRF, TJPI com citações.',           model: 'Perplexity llama-3.1', modelBadge: 'perp',  category: 'juridico',   project: 'juris',  color: '#6d28d9', active: true },
  { id: 'ben-especialista-compliance',name: 'BEN Especialista Compliance',    emoji: '🛡️', description: 'Conformidade LGPD, políticas de privacidade e proteção de dados.',   model: 'GPT-4o',             modelBadge: 'gpt',     category: 'juridico',   project: 'juris',  color: '#0f766e', active: true },
  { id: 'ben-relator-juridico',       name: 'BEN Relator Jurídico',           emoji: '📚', description: 'Artigos jurídicos, pareceres técnicos e publicações institucionais.', model: 'GPT-4o',             modelBadge: 'gpt',     category: 'juridico',   project: 'juris',  color: '#1e40af', active: true },
  { id: 'ben-redator-juridico',       name: 'BEN Redator Jurídico',           emoji: '✒️', description: 'Redação técnica jurídica, memorandos, ofícios e comunicações.',       model: 'GPT-4o',             modelBadge: 'gpt',     category: 'juridico',   project: 'juris',  color: '#374151', active: true },
  { id: 'ben-constitucionalista',     name: 'BEN Constitucionalista',         emoji: '⚡', description: 'MS, HC, Mandado de Injunção, ações constitucionais e STF.',           model: 'GPT-4o',             modelBadge: 'gpt',     category: 'juridico',   project: 'juris',  color: '#b91c1c', active: true },
  { id: 'ben-engenheiro-prompt',      name: 'BEN Engenheiro de Prompt',       emoji: '🧠', description: 'Otimização de prompts, configuração de agentes e arquitetura IA.',   model: 'GPT-4o',             modelBadge: 'gpt',     category: 'sistema',    project: 'juris',  color: '#4f46e5', active: true },
  { id: 'ben-contador-tributarista',                name: 'BEN Contador — Triagem',      emoji: '🧮', description: 'Triagem fiscal: classifica e encaminha ao especialista correto.',    model: 'Claude Haiku 4.5',   modelBadge: 'claude',  category: 'contador',   project: 'juris',  color: '#92400e', active: true },
  { id: 'ben-contador-tributarista-especialista',   name: 'BEN Contador — Especialista', emoji: '📊', description: 'Análise fiscal profunda — planejamento tributário avançado.',         model: 'Claude Sonnet 4.6',  modelBadge: 'sonnet',  category: 'contador',   project: 'juris',  color: '#b45309', active: true },
  { id: 'ben-contador-tributarista-planejamento',   name: 'BEN Contador — Planejamento', emoji: '🗺️', description: 'Planejamento tributário estratégico e otimização de carga.',           model: 'Claude Sonnet 4.6',  modelBadge: 'sonnet',  category: 'contador',   project: 'juris',  color: '#d97706', active: true },
  { id: 'ben-contador-tributarista-creditos',       name: 'BEN Contador — Créditos',     emoji: '💳', description: 'Recuperação de créditos tributários e compensações.',                 model: 'Claude Haiku 4.5',   modelBadge: 'claude',  category: 'contador',   project: 'juris',  color: '#059669', active: true },
  { id: 'ben-contador-tributarista-auditoria',      name: 'BEN Contador — Auditoria',    emoji: '🔍', description: 'Auditoria fiscal, conformidade tributária e gestão de risco.',        model: 'Claude Haiku 4.5',   modelBadge: 'claude',  category: 'contador',   project: 'juris',  color: '#dc2626', active: true },
  { id: 'ben-contador-tributarista-relatorio',      name: 'BEN Contador — Relatório',    emoji: '📋', description: 'Relatórios fiscais executivos e dashboards tributários.',              model: 'Claude Haiku 4.5',   modelBadge: 'claude',  category: 'contador',   project: 'juris',  color: '#0369a1', active: true },
  { id: 'ben-perito-forense',          name: 'BEN Perito Forense — Padrão',    emoji: '🔬', description: 'Análise pericial padrão — laudos e pareceres técnicos.',                  model: 'Claude Sonnet 4.6',  modelBadge: 'sonnet',  category: 'perito',     project: 'juris',  color: '#4f46e5', active: true },
  { id: 'ben-perito-forense-profundo', name: 'BEN Perito Forense — Profundo ⚠️', emoji: '🧬', description: 'Análise pericial profunda — alto custo, máxima precisão.',             model: 'Claude Opus 4.6',    modelBadge: 'opus',    category: 'perito',     project: 'juris',  color: '#b91c1c', active: true },
  { id: 'ben-perito-forense-digital',  name: 'BEN Perito Forense Digital',     emoji: '💻', description: 'Perícia digital e análise de evidências eletrônicas.',                   model: 'Claude Sonnet 4.6',  modelBadge: 'sonnet',  category: 'perito',     project: 'juris',  color: '#7c3aed', active: true },
  { id: 'ben-perito-forense-laudo',    name: 'BEN Perito Forense — Laudo',     emoji: '📄', description: 'Elaboração de laudos periciais técnicos para processos.',                model: 'Claude Haiku 4.5',   modelBadge: 'claude',  category: 'perito',     project: 'juris',  color: '#0369a1', active: true },
  { id: 'ben-perito-forense-contestar',name: 'BEN Perito — Contraditório',     emoji: '🛡️', description: 'Contestação de laudos adversariais e quesitos técnicos.',               model: 'Claude Haiku 4.5',   modelBadge: 'claude',  category: 'perito',     project: 'juris',  color: '#059669', active: true },
  { id: 'ben-perito-forense-relatorio',name: 'BEN Perito Forense — Relatório', emoji: '📊', description: 'Relatórios periciais executivos e sínteses técnicas.',                   model: 'Claude Haiku 4.5',   modelBadge: 'claude',  category: 'perito',     project: 'juris',  color: '#374151', active: true },
]
